#+TITLE: LJS Config Eshell
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[file:ljs-config.org][LJS-Config]]. These configurations borrow heavily from Kieran Healy's [[https://github.com/kjhealy/emacs-starter-kit][emacs starter-kit for
the social sciences]]. 


* Starter Kit Eshell
[[http://www.emacswiki.org/emacs/CategoryEshell][Eshell]] is a really great shell, actually.

** Basic Eshell Configuration
#+srcname: lexical-binding-cookie
#+begin_src emacs-lisp
;;; -*- lexical-binding: t; -*-
#+end_src

#+begin_src emacs-lisp
(use-package eshell :straight nil
  :init
  (setq eshell-cmpl-cycle-completions nil
        eshell-save-history-on-exit t
        eshell-cmpl-dir-ignore "\\`\\(\\.\\.?\\|CVS\\|\\.svn\\|\\.git\\)/\\'"
        eshell-history-ring-size 1000) ; Set the size of eshell-history-ring

  :config
  (eval-after-load 'esh-opt
    '(progn
       (require 'em-cmpl)
       (require 'em-prompt)
       (require 'em-term)
       ;; TODO: for some reason requiring this here breaks it, but
       ;; requiring it after an eshell session is started works fine.
       ;; (require 'eshell-vc)
       (setenv "PAGER" "cat")
       ; (set-face-attribute 'eshell-prompt nil :foreground "turquoise1")
       (add-hook 'eshell-mode-hook ;; for some reason this needs to be a hook
                 '(lambda () (define-key eshell-mode-map "\C-a" 'eshell-bol)))
       (add-to-list 'eshell-visual-commands "ssh")
       (add-to-list 'eshell-visual-commands "tail")
       (add-to-list 'eshell-command-completions-alist
                    '("gunzip" "gz\\'"))
       (add-to-list 'eshell-command-completions-alist
                    '("tar" "\\(\\.tar|\\.tgz\\|\\.tar\\.gz\\)\\'"))
       (add-to-list 'eshell-output-filter-functions 'eshell-handle-ansi-color))))

(add-hook 'eshell-mode-hook
          (lambda ()
            (require 'ansi-color)
            (add-hook 'eshell-preoutput-filter-functions 'ansi-color-filter-apply)))                    
#+end_src

** Eshell Autosuggest

#+begin_src emacs-lisp
(use-package esh-autosuggest
  :after eshell
  :hook (eshell-mode . esh-autosuggest-mode))
#+end_src

** 'Exec-Path-From-Shell Configuration

Handled once, centrally, in =ljs-config-appearance.org= now -- see the
note in ljs-config-python.org for why the other copies were removed.

** Set Zsh as DefaultShell for Eshell

#+begin_src emacs-lisp
(setq explicit-shell-file-name "/bin/zsh")
#+end_src


The =eshell= directory holds alias definitions and history
information.  It is much like a =.bashrc= file for those who are
familiar with bash.  This set the value of =eshell-directory-name= to
point to the =eshell= directory in this directory.  The =alias= file
is pre-populated with some generally applicable aliases.

#+begin_src emacs-lisp
  (setq eshell-directory-name (expand-file-name "./" (expand-file-name "eshell" dotfiles-dir)))
#+end_src


#+source: message-line
#+begin_src emacs-lisp
  (message "LJS Config Eshell loaded.")
#+end_src
