#+TITLE: LJS Config ELPA
#+OPTIONS: toc:nil num:nil ^:nil

This file is part of the [[file:ljs-config.org][Lindsay Stirton's Emacs Configurations]].


** Packages to Download

The following packages will be downloaded and installed. We separate
package installation and package configuration. This provides a
modular and consistent approach to package management, making it
easier to manage and update your Emacs configuration.

#+srcname: ljs-config-elpa-download-packages
#+begin_src emacs-lisp
  (use-package auctex)
  (use-package all-the-icons)
  (use-package all-the-icons-dired)
  (use-package cl-lib)
  (use-package csv-mode)
  (use-package doom-modeline)
  (use-package ebib)
  (use-package ess)
  (use-package all-the-icons)
  (use-package cl-lib)
  (use-package doom-modeline)
  (use-package exec-path-from-shell)
  (use-package flycheck)
  (use-package flyspell)
  (use-package forge)
  (use-package imenu)
  (use-package latex-pretty-symbols)
  (use-package magit)
  (use-package modus-themes)
  (use-package org-bullets)
  (use-package rainbow-delimiters)
  (use-package reftex)
  (use-package smartparens)
  (use-package thingatpt)
  (use-package smartparens)
  (use-package ess)
#+end_src


#+srcname: ljs-config-elpa-install-packages
#+begin_src emacs-lisp
(defun ljs-config-elpa-install ()
  "Install all ljs-config packages that aren't installed."
  (interactive)
  (dolist (package ljs-config-packages)
    (unless (or (member package package-activated-list)
                (functionp package))
      (message "Installing %s" (symbol-name package))
      (package-install package))))
#+end-src

#+srcname: ljs-config-esk-online
#+begin_src emacs-lisp
(when (and (functionp 'network-interface-list)
           (network-interface-list))
  (defun esk-online? ()
    "See if we're online."
    (cl-some (lambda (iface)
               (unless (equal "lo" (car iface))
                 (member 'up (first (last (network-interface-info
                                           (car iface)))))))
             (network-interface-list)))
  (when (esk-online?)
    (unless package-archive-contents
      (package-refresh-contents))
    (ljs-config-elpa-install)))
#+end-src

#+begin_src emacs-lisp
(message "ljs-config-elpa loaded.")
#+end-src
