#+TITLE: LJS Emacs Config
#+SEQ_TODO: PROPOSED TODO STARTED | DONE DEFERRED REJECTED
#+OPTIONS: H:2 num:nil toc:t
#+STARTUP: oddeven

* Introduction
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :END:

You are looking at the personal emacs configuration files of Lindsay
Stirton. Draws heavily (to the point of shameless plagiarism) on the
[[https://kieranhealy.org/resources/emacs-starter-kit/][Emacs Starter Kit for the Social Sciences]] (ESKSS), previously maintained by
[[http://kieranhealy.org][Kieran Healy]]. Quite apart from being a computer whizz, Healy is an
absolutely first rate social scientist. On the latter at least, I
speak with some authority, and a little envy. Read his work!

My aim is to provide a more minimal version than Healy's, while
incorporating some of my personal preferences, and in doing so learn a
bit about Emacs-Lisp programming. One important change since ESKSS was
actively developed has been the development of [[jwiegley.github.io/use-package][use-package]], which
greatly simplifies package-management. LJS Emacs Config makes maximal
use of use-package.

Source code for the latest version is at
http://lindsaystirton.github.com/ljs-config/.



** Installation
   :PROPERTIES:
   :CUSTOM_ID: installation
   :END:

*** Before you Begin
If you have used Emacs before and already have a =.emacs= file or =.emacs.d= directory, back them up and then delete them. See below for details on how to add customizations to the kit.

*** Getting Lindsay's Emacs
You have two choices. 

/Option A/. Download [add link] a =.zip= file of ljs-config. 

/Option B/. If you want to keep up with changes to the configurations,
you should clone the source code using git rather than simply copying
a static version of it. In general I think you should be using version
control on your plain-text documents anyway, so I recommend this
option. The most straightforward way to get the tools you need is to
*install Xcode*. Xcode is what software developers use to write Mac
and iOS applications. As such it comes with a bunch of things we are
not so interested in, but it makes it easy to install the tools we do
need. It's available for free [[https://developer.apple.com/xcode/][via the Mac App Store]]. Once downloaded,
launch Xcode, go to Xcode &#62; Preferences &#62; Downloads and
install the *Command Line Tools for Xcode*. At that point you can quit
Xcode and never use it again. Alternatively, go to [[https://developer.apple.com][Apple's Developer
Site]], login with your Apple ID and download the Command Line Tools
for Xcode package by itself, without the Xcode application.

*** Prerequisites

*0.1 Get Emacs*.  [[http://emacsformacosx.com][Download Emacs here]].

*0.2 Install a Modern TeX Distribution*. If you are using OS X,
[[http://tug.org/mactex/][download MacTeX]] and install it.

*0.3 Install R and Pandoc*. These are not strictly required for the
installation to work, and you can skip this step if you like. But you
will probably be using them anyway, if you're not already. If you're
doing statistical work you will probably want to use R or Stata. R is
free and you can [[http://www.r-project.org][download it here]]. Pandoc is a very useful utility
that lets you convert easily between many different forms of
plain-text markup (such as Markdown, HTML, LaTeX, and
others). [[johnmacfarlanet/pandoc/][Get Pandoc here]].

*0.4 Note your user name*. If you don't know it, open the Terminal
application and do

#+begin_src sh
 whoami
#+end_src

You will need this to activate your own personal customisation file
-- see the "Per-user customisations" note near the end of this
document.

*** Setup

*1.* If you downloaded a =.zip= file of the kit, you must uncompress it, move the resulting folder to the top level of your home director and rename it =.emacs.d=. Assuming the downloaded zip file is in your =~/Downloads= folder, open a Terminal window and do this:

#+begin_src sh
 cd ~/Downloads
 unzip ljs-config-master.zip
 mv ljs-config-master ~/.emacs.d
#+end_src

Alternatively, if you are using git (the preferred method), then clone the starter kit from github. Open a Terminal window and do this:


#+begin_src sh
 git clone git://github.com/lindsaystirton/ljs-config ~/.emacs.d
#+end_src

*2.* Inside the file =ljs.org=, change the paths to any BibTeX databases as described at the top of that file.


*3.* Rename the starter kit's =ljs.org= file to that of
=%your-username%.org= or =%your-systemname%.org=, based on the
information you noted in 0.4 above. This is where you can add in any
of your own further customizations to Emacs.


*4.* Launch Emacs.

When you first start Emacs after installing Lindsay's Emacs, it will
try to contact several package repositories, so make sure you have an
internet connection. The kit will download packages mainly from the
official [[http://http://elpa.gnu.org][GNU ELPA Repository]] and the [[MELPA Repo]]. Each package will be
fetched, compiled by Emacs, and stored in the =~/.emacs.d=
directory. In practice I've found that this process is prone to
hiccups as packages are fetched from the servers, so please be patient
with it. If it doesn't get everything first time around, quit and
relaunch Emacs, and it will try again. If the problem
persists---especially if you get a message saying "The package
'auctex' is not available for installation"---you can manually install
packages as follows. Open Emacs, do =M-x list-packages= and in the
resulting buffer search or scroll down the list to, e.g., auctex, mark
it for installation by pressing =i= and then install it (or them) by
hitting =x=. With the packages in place, restart Emacs and the starter
kit will finish setting itself up. Unfortunately, I can't control
these intermittent installation errors. They seem to have something to
do with the way Emacs talks to the GNU ELPA package server.

*5.* (Optional.) Once Emacs is up and running, do =M-x
ljs-config-compile= to byte-compile all the emacs-lisp (.el)
files that form part of my emacs configuration, for slightly faster
loading.

** Structure
   :PROPERTIES:
   :CUSTOM_ID: structure
   :END:

The init.el file is where everything begins. It's the first file to
get loaded. Additional customization embedded in this file provides
what I consider to be better defaults, both for different programming
languages and for built-in Emacs features like bindings or registers.

These configurations were written (or more accurately adapted) for
Emacs 29.1, and makes use of Emacs' package system to install a number
of additional packages. These are stored in =~/.emacs.d/elpa=. Some
useful packages are not available through the package manager
yet. These are stored in =~/.emacs.d/src/=.

There are also a few files that are meant for code that doesn't belong
in ljs-config, they are described below in [[* Customization][Customization]]

** Customization
   :PROPERTIES:
   :CUSTOM_ID: customization
   :END:

The many defaults built into these configuration files are only the
beginning of most users customization of Emacs to suite their needs.
The starter kit provides a number of places for additional user and
system specific customization.  These are designed in such a way that
it will be easy for you to continue tracking your own personal
customization inside ljs-config while retaining your ability to
pull down general ljs-config updates without conflict.

- Make your own branch :: The first step to user-specific
     customization is (like in any git project) to make a branch for
     your local changes using =git branch=.  Save the master branch
     for pulling down new versions of the starter kit, and save all of
     your personal information in a personal branch.  That way you
     never have to worry about accidentally =git push='ing up a patch
     with all of your gnus email passwords.

- Per-user config :: Personal, machine-specific settings -- a
     bibliography path, `org-directory' -- go in a file named after
     your user login name, with a =.org= extension, living alongside
     this file (=ljs-config/<username>.org=). It's loaded
     automatically on startup if it exists, and silently skipped if
     it doesn't. If you're unsure of your user name:
     #+begin_src sh
       whoami
     #+end_src
     =ljs46.org= and =ljs.org=, in this same directory, are Lindsay's
     own real examples of what one looks like -- see the audit, §41,
     for the fuller reasoning behind keying this on username rather
     than on the machine's hostname.

- Installing more elisp libraries :: While my includes
     many useful Emacs lisp libraries, you are bound to find more that
     you will want to install.  The easiest way to install new
     libraries is through the Emacs Lisp Package Archive (see [[* elpa][ELPA]]).
     When a library is not available through ELPA you can grab its
     source and place it directly in the =src= directory.  Any
     packages found there will automatically be added to your
     load-path when Emacs starts up.
     
Some additional miscellaneous configuration and getting started
suggestions
- First off see the [[http://www.gnu.org/software/emacs/manual/html_node/emacs/Customization.html#Customization][Customization]] node in the Emacs manual.  Available
  online or through the =info= command (run with =C-h i=).
- =grep=-ing through the =ljs-config-*= files in this directory can
  provide useful examples for how to do things like install major
  modes, define keybindings, etc..
- read the following [[http://www.gnu.org/software/emacs/elisp/html_node/Key-Binding-Conventions.html][Key-Binding-Conventions]] before defining too many
  personal key bindings
- The starter-kit comes pre-bundled with a variety of color themes.
  See [[file:starter-kit-misc.org::*Color%20Themes][Color Themes]] for instructions on how to change the colors used
  by Emacs.
  
** Emacs Lisp Package Archive
   :PROPERTIES:
   :CUSTOM_ID: elpa
   :END:

Libraries from [[http://elpa.gnu.org/packages/][ELPA]] or the [[http://melpa.milkbox.net/][MELPA]] repo are preferred when available since dependencies
are handled automatically, and the burden to update them is removed
from the user. 

Sometimes packages are removed from the Starter Kit as they get added
to ELPA itself. This has occasionally caused problems with certain
packages. If you run into problems with such a package, try removing
everything from inside the elpa/ directory and invoking =M-x -elpa-install= in a fresh instance.

* Implementation
  :PROPERTIES:
  :CUSTOM_ID: implementation
  :END:
This section contains all code implementing Lindsay's emacs configuration.

** ljs-config basics

#+name: ljs-config-load-on-startup
#+name: lexical-binding-cookie
#+begin_src emacs-lisp
;;; -*- lexical-binding: t; -*-
#+end_src

*** Preamble: where Customize saves things

Moved here from =init.el= as part of the init.el/early-init.el
minimisation (see the audit, §31) -- nothing about this needs to run
before Org itself loads, only before Customize might try to save or
load something, and this file runs immediately after =init.el='s
bootstrap with no gap in between.

#+begin_src emacs-lisp
(setq custom-file (concat dotfiles-dir "custom.el"))
#+end_src

*** straight.el bootstrap (package-manager migration, Phase 2, moved after first restart)

Two real bugs turned up on the first restart after Phase 2, both fixed
here rather than patched around:

1. *Ordering bug.* This block used to sit down in the old ELPA
   section, after "Ubiquitous Packages" and after
   ljs-config-aspell.org were already loaded. Those files' bare
   =(use-package cl-lib :straight nil)=-style declarations (cl-lib,
   ffap, uniquify, ansi-color, recentf, saveplace, flyspell) ran
   before straight had ever taught =use-package= what =:straight=
   even means, so they all failed with "Unrecognized keyword:
   :straight". Fixed by moving this whole block to the very top of
   the Implementation section, before anything else that uses
   =use-package= loads.
2. *org-mode fetch failure.* Even with =(use-package org :straight
   nil ...)= correctly in place in ljs-config-latex.org and
   ljs-config-org.org, Emacs's init crashed outright trying to `git
   clone` =emacs-straight/org-mode= -- because =:straight nil= on our
   own declarations only opts *those* out; it does nothing about
   other straight-managed packages (org-roam, most likely) that list
   =org= as a dependency and would otherwise make straight fetch it
   regardless. The standard fix, and a well-documented gotcha for
   straight.el + org-roam specifically: register an explicit recipe
   for =org= as satisfied by whatever ships built into Emacs, before
   anything else can ask straight for it.

#+name: ljs-config-straight-bootstrap
#+begin_src emacs-lisp
  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name
          "straight/repos/straight.el/bootstrap.el"
          (or (bound-and-true-p straight-base-dir)
              user-emacs-directory)))
        (bootstrap-version 7))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

  (straight-use-package 'use-package)
  ;; Tell straight org is satisfied by the Emacs-bundled version,
  ;; before any other package (org-roam in particular) can ask
  ;; straight to go fetch it from emacs-straight/org-mode instead.
  (straight-use-package '(org :type built-in))
  (setq straight-use-package-by-default t)
#+end_src

*** Fix macOS GUI Emacs's PATH, before anything else needs it

macOS GUI Emacs doesn't inherit the shell's PATH the way Terminal
does, so anything installed via Homebrew is invisible to Emacs until
something fixes this. It has to happen this early, right after the
straight.el bootstrap and before anything else: jinx (next section,
=ljs-config-spelling.org=) needs =pkg-config= and =enchant= on PATH
to build its native module the very first time it loads, and
"Ubiquitous Packages" immediately below already does an
=executable-find= for Homebrew's =gls=. Previously this lived much
later, in =ljs-config-appearance.org= (loaded fifth) -- too late for
either of those, and the reason jinx's build failed with "pkgconf or
pkg-config not found" the first time it was tried, even though both
were installed via Homebrew (see the audit, §43). A second, inert
(=:tangle no=) copy documented as optional in =ljs-config-latex.org=
is left alone -- it was never actually live.

#+name: ljs-config-exec-path-from-shell
#+begin_src emacs-lisp
(use-package exec-path-from-shell
  :if (memq window-system '(mac ns x))
  :config
  ;; macOS GUI Emacs doesn't inherit your shell's PATH by default, so
  ;; without this, anything installed via Homebrew (or asdf, pyenv,
  ;; etc) can be invisible to Emacs even though it works fine in
  ;; Terminal. This also means paths elsewhere in this config never
  ;; need to hardcode a specific Homebrew prefix (/opt/homebrew vs
  ;; /usr/local) -- whichever one is on your shell's PATH is the one
  ;; Emacs will find.
  (exec-path-from-shell-initialize))
#+end_src

*** Ubiquitous Packages

These should be loaded on startup rather than autoloaded on demand
since they are likely to be used in every session

#+begin_src emacs-lisp 

  ;;; Ubiquitous Packages
    (require 'use-package)

    (use-package cl-lib
      :straight nil)

    (use-package ffap
      :straight nil)

    (use-package uniquify
      :straight nil
      :demand t
      :config
      (setq uniquify-buffer-name-style 'forward))

    (use-package ansi-color
      :straight nil)

    (use-package recentf
      :straight nil
      :config
      (recentf-mode 1))

    (use-package saveplace
      :straight nil
      :config
      (save-place-mode 1))

    ;; A handful of small, universal preferences folded in from the
    ;; old, never-actually-loaded ljs46.org (see the audit, §41) --
    ;; none of these are personal or machine-specific, they're just
    ;; preferences, true on every machine this config runs on.

    ;; OS X ships BSD ls, which dired wants GNU ls's extra features
    ;; for. Use it if `brew install coreutils' has put it on PATH;
    ;; harmless no-op otherwise.
    (when (executable-find "gls")
      (setq insert-directory-program (executable-find "gls")))

    ;; M-e sentence navigation without two spaces after a period.
    (setq sentence-end-double-space nil)

    ;; Keep scrolling to follow compilation output.
    (setq compilation-scroll-output t)

    ;; Minimize the fringe indicator for empty lines at buffer end.
    (setq-default indicate-empty-lines nil)

    ;; Comment/uncomment the region with either binding.
    (global-set-key (kbd "C-c ;") 'comment-or-uncomment-region)
    (global-set-key (kbd "M-'") 'comment-or-uncomment-region)

    ;; Start `cd'd to home rather than wherever Emacs happened to launch.
    (cd "~/")

    ;; Was a hand-edited `custom-set-variables' kludge in the old
    ;; ljs46.org -- that mechanism is meant to be machine-written by
    ;; Customize, not hand-maintained; these are just plain settings.
    ;; (The two AUCTeX-specific values from that same kludge,
    ;; TeX-engine and LaTeX-XeTeX-command, live in
    ;; ljs-config-latex.org instead, alongside the rest of AUCTeX's
    ;; configuration.)
    (setq blink-cursor-mode nil)
    (setq text-mode-hook '(text-mode-hook-identify))
#+end_src

*** Function for loading/compiling ljs-config-*
#+name: ljs-config-load
#+begin_src emacs-lisp 
  (defun ljs-config-load (file)
    "This function is to be used to load ljs-config-*.org files."
    (org-babel-load-file (expand-file-name file
                                           dotfiles-dir)))
#+end_src

#+name: ljs-config-compile
#+begin_src emacs-lisp
  (defun ljs-config-compile (&optional arg)
    "Tangle and Byte compile all ljs-config files."
    (interactive "P")
    (cl-flet ((age (file)
                (float-time
                 (time-subtract (current-time)
                                (nth 5 (or (file-attributes (file-truename file))
                                           (file-attributes file)))))))
      (mapc
       (lambda (file)
         (when (string= "org" (file-name-extension file))
           (let ((el-file (concat (file-name-sans-extension file) ".el")))
             (when (or arg
                       (not (and (file-exists-p el-file)
                                 (> (age file) (age el-file)))))
               (org-babel-tangle-file file el-file "emacs-lisp")
               (byte-compile-file el-file)))))
       (apply #'append
              (mapcar
               (lambda (d)
                 (when (and (file-exists-p d) (file-directory-p d))
                   (mapcar (lambda (f) (expand-file-name f d)) (directory-files d))))
               (list (concat dotfiles-dir user-login-name) dotfiles-dir))))))
#+end_src






*** LJS Config Spelling
Fast, syntax-aware spell-checking via jinx -- located in [[file:ljs-config-spelling.org][ljs-config-spelling]]
#+begin_src emacs-lisp
  (ljs-config-load "./ljs-config/ljs-config-spelling.org")
#+end_src




*** ELPA (Emacs Lisp Package Manager)

[[http://elpa.gnu.org/][Emacs List Package Archive]] (ELPA).

#+name: ljs-config-package
#+begin_src emacs-lisp 

  ;; package.el retired here as of Phase 2 of the straight.el migration
  ;; (see the audit, sections 4 and 6). All package fetching and
  ;; activation is now handled by straight.el, bootstrapped near the
  ;; top of this file (see the "straight.el bootstrap" section
  ;; above), so
  ;; this block no longer calls `require' on `package', sets
  ;; `package-archives', or calls `package-initialize' -- keeping
  ;; package.el active alongside straight.el would make both package
  ;; managers try to install the same packages at once (see
  ;; radian-software/straight.el issue #425). Emacs's own automatic
  ;; startup activation of package.el is separately disabled in
  ;; early-init.el via `package-enable-at-startup'.

#+end_src

#+name: ljs-config-load-packages
#+begin_src emacs-lisp
    (ljs-config-load "./ljs-config/ljs-config-packages.org")
 #+end_src

 #+results: ljs-config-packages
: loaded ljs-config-packages.el
#+end_src


*** hash keybinding

Putting this here for now. Eventually we will have ljs-org-bindings. 

#+name: ljs-config-osX-workaround
#+begin_src emacs-lisp 
 (global-set-key (kbd "M-3") (lambda () (interactive) (insert "#")))
#+end_src

*** Per-user customisations

The rest of this config is identical for anyone who clones it. This
is the one place that isn't: a small, tracked, per-username override
file -- =ljs46.org= for the MacBook and office iMac, =ljs.org= for
the Mac Mini, keyed on =user-login-name= rather than the machine's
hostname, since that's the identity that actually varies here (the
same person, three machines, two different OS usernames -- see the
audit, §41, for the fuller reasoning). Anything that names a real
location on disk -- a bibliography path, `org-directory' -- lives in
whichever of these two files matches the machine you're on; nothing
else should.

This mechanism previously existed (as =user-specific-config=/
=user-specific-literate-config=) but was broken two ways at once: it
pointed at the wrong path (missing the =ljs-config/= directory
component, so it looked for =~/.emacs.d/ljs46.org= when the file
actually lives at =~/.emacs.d/ljs-config/ljs46.org=), and nothing
ever actually loaded it even if the path had been right. A parallel
hostname-keyed slot (=system-specific-config=) existed alongside it
for machine-specific rather than person-specific settings -- removed
here rather than fixed, since nothing turned out to need it: the one
thing that genuinely varies by screen rather than by account (the
initial frame size) is now detected dynamically instead (see
=ljs-config-appearance.org=), so there's nothing left for a
hostname-keyed file to hold.

On someone else's machine, or a fresh clone before you've made your
own =<your-username>.org=, this is silently skipped -- see the
README.

#+name: ljs-config/user-setup
#+begin_src emacs-lisp 
  (setq user-specific-config (concat dotfiles-dir "ljs-config/" user-login-name ".el")
        user-specific-literate-config (concat dotfiles-dir "ljs-config/" user-login-name ".org"))
  (when (file-exists-p user-specific-literate-config)
    (ljs-config-load user-specific-literate-config))
#+end_src

You can keep elisp source in the =src= directory.  Packages loaded
from here will override those installed by ELPA.  This is useful if
you want to track the development versions of a project, or if a
project is not in elpa.

#+name: ljs-config-load-elisp-dir
#+begin_src emacs-lisp
(setq elisp-source-dir (concat dotfiles-dir "src"))
(add-to-list 'load-path elisp-source-dir)
#+end_src

** Load the rest of ljs-config core
The following files contain the remainder of the core of the core
ljs-config.  All of the code in this section should be loaded.


*** LJS Config Defuns
LJS Config function definitions in [[file:ljs-config-defuns][ljs-comfig-defuns]].
#+name: ljs-config-load-defuns
#+begin_src emacs-lisp
(ljs-config-load "./ljs-config/ljs-config-defuns.org")
#+end_src

*** LJS Config Dired
Buffer/file listing -- located in [[file:ljs-config-dired.org][ljs-config-dired]]
#+name: ljs-config-load-dired
#+begin_src emacs-lisp
  (ljs-config-load "./ljs-config/ljs-config-dired.org")
#+end_src

*** LJS Config Appearance
[[file:ljs-config-appearance.org][ljs-config-appearance]].
#+name: ljs-config-load-appearance
#+begin_src emacs-lisp
  (ljs-config-load "./ljs-config/ljs-config-appearance.org")
#+end_src

*** LJS Config Completion
[[file:ljs-config-completion.org][ljs-config-completion]].
#+name: ljs-config-load-completion
#+begin_src emacs-lisp
  (ljs-config-load "./ljs-config/ljs-config-completion.org")
#+end_src

*** LJS Config Bibliography
Located in [[file:ljs-config-bibliography.org][ljs-config-bibliography]]

#+name: ljs-config-load-bibliography
#+begin_src emacs-lisp
  (ljs-config-load "./ljs-config/ljs-config-bibliography.org")
#+end_src

*** LJS Config LaTeX
Located in [[file:ljs-config-latex.org][ljs-config-latex]]

#+name: ljs-config-load-latex
#+begin_src emacs-lisp
  (ljs-config-load "./ljs-config/ljs-config-latex.org")
#+end_src

*** Starter Kit Stats
Located in [[file:ljs-config-stats.org][ljs-config-stats]]

#+begin_src emacs-lisp
  (ljs-config-load "./ljs-config/ljs-config-stats.org")
#+end_src

*** Starter Kit Text
Located in [[file:ljs-config-text.org][ljs-config-text]]

#+begin_src emacs-lisp
  (ljs-config-load "./ljs-config/ljs-config-text.org")
#+end_src


*** LJS Config Git
Located in [[file:ljs-config-git.org][ljs-config-git]]

#+name: ljs-config-load-git
#+begin_src emacs-lisp
  (ljs-config-load "./ljs-config/ljs-config-git.org")
#+end_src


*** LJS Config Org
Located in [[file:ljs-config-org.org][ljs-config-org]]

#+name: ljs-config-load-org
#+begin_src emacs-lisp
  (ljs-config-load "./ljs-config/ljs-config-org.org")
#+end_src

*** *LJS Config Eshell
Located in [[file:ljs-config-eshell.org][ljs-config-eshell]]

#+name: ljs-config-load-eshell
#+begin_src emacs-lisp
  (ljs-config-load "./ljs-config/ljs-config-eshell.org")
#+end_src

*** LJS Config Python
Located in [[ljs-config-python.org][ljs-config-python]]

#+name: ljs-config-load-python
#+begin_src emacs-lisp
  (ljs-config-load "./ljs-config/ljs-config-python.org")
#+end_src

*** LJS Config Lisp
Located in [[ljs-config-lisp.org][ljs-config-lisp]]

#+name: ljs-config-load-lisp
#+begin_src emacs-lisp
  (ljs-config-load "./ljs-config/ljs-config-lisp.org")
#+end_src




#+name: message-line
#+begin_src emacs-lisp
  (message "LJS Config main file loaded.")
#+end_src


